### ISSUE TITLE
can't run preprocess_open_subtitles.py

### ISSUE THREAD

**Issue by Miki0617** [kkenealy/Adversarial-Learning-for-Neural-Dialogue-Generation#1]
我通过anaconda安装了 python 3.6和 tensorflow 2.0，运行代码时遇到了一些问题
显示报错 Process finished with exit code -1073741819 (0xC0000005)
试了一下，以下方法无效：h5py 升级到 2.9.0
分析可能是以下原因：
Line 2: 
from tensorflow.python.platform import gfile
显示无法找到gfile，查了一下tf2.0的 Gfile 在 tf.io 下，但我site-package下的 tensorflow 文件夹下没有 io 包

---
Line 19
with gfile.GFile("./data/en.txt", mode="r") as raw:
这个 en.txt 是什么

---
另外想问一下下载的语料集是6个txt文件，我应该使用哪一个用于训练

感谢你的帮助

**Comment by kkenealy** [comment]
I'm not sure that I can help you with your gfile import issue. I have tensorflow 2.0 and python 3.6 and can import gfile as specified in line 2 with no problems. After searching online, it seems like you might have an issue with your python installation (see https://stackoverflow.com/questions/33582766/process-finished-with-exit-code-1073741515-0xc0000135). I would try to open python in your terminal window and try to get the line from tensorflow.python.platform import gfile working in your terminal, and then try running again.

In addition, I've updated the README with more specific instructions on how to get the data into the file as specified above.

**Comment by Miki0617** [comment]
thanks a lot~
